---

- hosts: all
  gather_facts: yes

- name: Configuring Loadbalancer
  hosts: HAproxy
  become: yes
  tasks:

    - name: Installing HAproxy
      apt:
        name: haproxy
        state: present
        update_cache: true


    - name: gather server ip addresses
      setup:
        filter: ansible_default_ipv4.address


    - name: copy files haproxy.cfg
      template:
        src: haproxy.cfg.j2
        dest: "/etc/haproxy/haproxy.cfg"
      notify:
        - restart haproxy

  handlers:

    - name: restart haproxy
      service:
        name: haproxy
        state: restarted

- hosts: webservers
  become: yes
  tasks:
    - name: install pip
      apt:
        name: python3-pip
        state: present

    - name: install flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: create new directory
      file:
        path: "/home/flask-app/"
        state: directory

    - name: copy app.py to webservers
      template:
        src: "application2.py"
        dest: "/home/flask-app/app.py"

    - name: start flask app
      shell: |
        cd /home/flask-app/
        export FLASK_APP=app.py
        flask run --host=0.0.0.0 --port=80&
